unzip daily-anekdot-bot-render.zip
cd daily-anekdot-bot

git init
git remote add origin https://github.com/ТВОЙ_ЮЗЕРНЕЙМ/ИМЯ-РЕПО.git
git add .
git commit -m "Initial commit"
git branch -M main
git push -u origin main
